
  - name: Ensure system-wide vim config only so users can set own preferences 
    lineinfile: 
      line: |
        {{ item }}
      dest: "{{ vimrc_root_directory}}/vimrc"
      owner: root 
      group: root 
      mode: 644
    become: yes
    with_items: "{{ vim_config }}"

  - name: Ensure Vim Plugin directory exists
    file: path={{ vimrc_root_directory}} state=directory owner=root group=root
    become: yes

  - name: create archive for vimRC Plugin files
    local_action: shell chdir={{ roles_path }}/vimrc/files/ tar cvfz vimfiles.tgz vim/files/*;
    become: no

  - name: create archive for vimRC Plugin files
    local_action: shell chdir={{ roles_path }}/ ls -la
    become: no

  - name: Copy VimRC Plugins
    unarchive: src="{{ roles_path }}/vimrc/files/vimfiles.tgz" dest="{{ vimrc_root_directory }}"
    become: yes

  - name: Ensure Vim Plugin Permissions
    file: path={{ vimrc_root_directory}} state=directory owner=root group=root recurse=yes
    become: yes
